version: '3.9'

services:

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: retails-analysis-backend
    volumes:
      - ./:/apps/
  
  mongo:
    image: mongo:${MONNGO_VERSION:-latest}
    container_name: retails-analysis-mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONNGO_USER:-root}
      MONGO_INITDB_ROOT_PASSWORD: ${MONNGO_PWD:-root}

  mongo-express:
    image: mongo-express
    container_name: retails-analysis-mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONNGO_USER:-root}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONNGO_PWD:-root}
      ME_CONFIG_MONGODB_URL: mongodb://root:${MONNGO_PWD:-root}@mongo:27017/
