version: '3.9'

services:

  retails-analysis-api:
    build:
      context: .
      dockerfile: prod.Dockerfile
    container_name: retails-analysis-api
    depends_on:
      - mongo
      - spark-master
    ports:
      - 80:80
      - 8888:8888
    # volumes:
    #   - ./:/apps/

  spark-worker:
    image: bitnami/spark:${SPARK_VERSION:-latest}
    container_name: retails-analysis-spark-worker
    restart: always
    depends_on:
      - spark-master
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
  spark-master:
    image: bitnami/spark:${SPARK_VERSION:-latest}
    container_name: retails-analysis-spark-master
    restart: always
    ports:
      - 8080:8080
      - 7077:7077
    environment:
      - SPARK_MODE=master

  mongo:
    image: mongo:${MONNGO_VERSION:-latest}
    container_name: retails-analysis-mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONNGO_USER:-root}
      MONGO_INITDB_ROOT_PASSWORD: ${MONNGO_PWD:-root}

  mongo-express:
    image: mongo-express
    container_name: retails-analysis-mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONNGO_USER:-root}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONNGO_PWD:-root}
      ME_CONFIG_MONGODB_URL: mongodb://root:${MONNGO_PWD:-root}@mongo:27017/
